[Fix] Current Server 관련 로그 추가

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -125,8 +125,12 @@ jobs:
           script_stop: true
           script: |
             echo "Stopping current server: ${{env.CURRENT_UPSTREAM}}"
+            echo "Checking if container ${{env.CURRENT_UPSTREAM}} exists..."
+            sudo docker ps -a --format '{{.Names}}' | grep -E "^${{env.CURRENT_UPSTREAM}}$" || echo "Container not found."
             if [ "${{env.CURRENT_UPSTREAM}}" != "default_env" ] && sudo docker ps -a --format '{{.Names}}' | grep -Eq "^${{env.CURRENT_UPSTREAM}}$"; then
+              echo "Stopping and removing container ${{env.CURRENT_UPSTREAM}}"
               sudo docker stop ${{env.CURRENT_UPSTREAM}} && sudo docker rm ${{env.CURRENT_UPSTREAM}};
             else
               echo "Container ${{env.CURRENT_UPSTREAM}} does not exist. Skipping stop and remove.";
             fi
+
